services:
  nuxt:
    image: 309050103249.dkr.ecr.us-east-2.amazonaws.com/mhartzell/time-flies:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      NITRO_PORT: 3000
      HOST: 0.0.0.0      
      DATABASE_URL: "${DATABASE_URL}"

